import { DECISION_STATUS } from "./domain.mjs";
import { recordHumanDecision } from "./decisions.mjs";
import { buildDashboard } from "./dashboard.mjs";
import { DEMO_NETWORK } from "./demo-data.mjs";
import { LEDGER_EVENT, replayLedger, photoRetentionState } from "./ledger.mjs";
import { openPilotStore, loadLedger, appendLedger, saveRegisterPhoto, markRegisterPhotoVerified, listPhotoMetadata, purgeExpiredRegisterPhotos } from "./browser-storage.mjs";
import { loadShopProfile, saveShopProfile, loadCatalogue, replaceCatalogue, replaceLedger } from "./browser-storage.mjs";
import { reviewOperationalCsv, productAdvice } from "./field-pilot.mjs";

let network = DEMO_NETWORK;
let dashboard = buildDashboard(network);
let pilotDb = null;
let ledgerEvents = [];
let persistenceError = null;
let shopProfile = null;
let catalogue = [];
const decisions = new Map();

function el(tag, text = "", className = "") { const node = document.createElement(tag); if (text !== "") node.textContent = String(text); if (className) node.className = className; return node; }
function button(text, className = "secondary") { return el("button", text, className); }
function badge(text, tone = "neutral") { return el("span", text, `badge ${tone}`); }
function firstShopRow() { return dashboard.shops[0]; }
function demoNow() { return new Date().toISOString(); }
function formatSource(source = "UNKNOWN") { if (source.startsWith("COUNT:")) return "physical stock check"; if (source.startsWith("DELIVERY")) return "stock receipt"; if (source === "DEMO_POS_EXPORT") return "POS export"; if (source === "DEMO_PHYSICAL_COUNT") return "physical count"; return source.replaceAll("_", " ").toLowerCase(); }
function fact(label, value) { const n = el("div", "", "fact"); n.append(el("span", label), el("strong", value)); return n; }
function sectionHead(title, copy) { const h = el("div", "", "section-heading"); const d = el("div"); d.append(el("p", "DATA INTAKE", "eyebrow"), el("h2", title)); h.append(d, el("p", copy)); return h; }

function refresh() { network = replayLedger(DEMO_NETWORK, ledgerEvents); dashboard = buildDashboard(network); document.querySelector("#mode-label").textContent=shopProfile?`${shopProfile.shopName} · local pilot`:"Synthetic demo · no live orders"; renderToday(); renderUpdate(); renderProducts(); renderDistributor(); }
function makeId(prefix) { return `${prefix}-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(16).slice(2)}`}`; }
async function persistOperationalEvent(eventType, quantity, { source = "KIRANAFLOW_UI", evidencePhotoId = null } = {}) { if (!pilotDb) throw new Error("Persistent store is unavailable"); const shop = network.shops[0], event = { eventId: makeId("EVT"), shopId: shop.shopId, skuId: shop.skuId, eventType, quantity, occurredAt: demoNow(), source, evidencePhotoId }; await appendLedger(pilotDb, event); ledgerEvents = await loadLedger(pilotDb); refresh(); return event; }

function renderToday() {
  const root = document.querySelector("#today-view"); root.replaceChildren(); const row = firstShopRow();
  if(shopProfile&&catalogue.length){renderFieldToday(root);return;}
  const hero = el("div", "", "welcome premium-hero"), heroCopy = el("div", "", "hero-copy"), heroImage = document.createElement("img"); heroCopy.append(el("p", row.shop.name, "eyebrow"), el("h1", "What needs your attention today?"), el("p", "Update what is in the shop. KiranaFlow checks the risk. You decide what to do.", "subtitle")); heroImage.src = "./assets/kirana-hero.jpg"; heroImage.alt = "Illustrated Indian neighbourhood kirana shop shelves and counter"; heroImage.className = "hero-art"; hero.append(heroCopy, heroImage); root.append(hero);
  const flow = el("div", "", "workflow-strip"); [["1","Update stock"],["2","We check risk"],["3","Review suggestion"],["4","You decide"]].forEach(([n,label])=>{const step=el("div","","workflow-step");step.append(el("span",n),el("strong",label));flow.append(step);}); root.append(flow);
  const summary = el("div", "", "attention-grid"); const factors = row.exceptions?.factors ?? []; const high = factors.filter((f) => f.severity === "HIGH").length;
  const attention = el("button", "", "attention-card urgent"); attention.append(el("span", String(Math.max(1, high)), "attention-number"), el("strong", "item needs attention"), el("span", "Review the demonstrated SKU", "muted")); attention.addEventListener("click", () => document.querySelector("#decision-card")?.scrollIntoView({ behavior: "smooth" }));
  const data = el("button", "", "attention-card data"); data.append(el("span", "✓", "attention-number"), el("strong", "stock evidence available"), el("span", `From ${formatSource(row.shop.inventoryEvidence?.source)}`, "muted")); data.addEventListener("click", () => showTab("update")); summary.append(attention, data); root.append(summary);
  if (!row.inventoryPolicy || !row.recommendation || !row.exceptions?.recommendationAllowed) { const blocked = el("section", "", "decision-card blocked"); blocked.append(el("p", "CHECK STOCK FIRST", "eyebrow danger-text"), el("h2", row.shop.productName), el("p", "The evidence is missing, stale or conflicting. KiranaFlow will not give a confident order quantity until stock is checked.")); const update = button("Update stock", "primary"); update.addEventListener("click", () => showTab("update")); blocked.append(update); root.append(blocked); return; }
  const d = el("section", "", "decision-card"); d.id = "decision-card"; const cover = row.inventoryPolicy.daysCover === null ? "unknown" : `${row.inventoryPolicy.daysCover.toFixed(1)} days`;
  d.append(badge("ACT NOW", "danger"), el("h2", row.shop.productName), el("div", `${row.shop.onHand}`, "stock-number"), el("p", `${row.shop.unit}${row.shop.onHand === 1 ? "" : "s"} currently recorded`, "stock-unit"));
  const freshness = el("div", "", "freshness"); freshness.append(el("span", "●", "fresh-dot"), el("span", `Stock evidence: ${formatSource(row.shop.inventoryEvidence?.source)} · ${row.shop.inventoryEvidence?.observedAt ?? "time unknown"}`)); d.append(freshness, el("h3", "Likely to run short before the next normal delivery."));
  const facts = el("div", "", "fact-grid"); facts.append(fact("Stock cover", cover), fact("Supplier lead time", `${row.shop.leadTimeMeanDays} days`), fact("Forecast demand", `${row.forecast.forecast.toFixed(1)} / day`)); d.append(facts);
  const suggestion = el("div", "", "suggestion"); suggestion.append(el("span", "Suggested review", "muted"), el("strong", `${row.recommendation.proposedQuantity} ${row.shop.unit}s`)); d.append(suggestion);
  const details = document.createElement("details"); details.className = "why"; details.append(el("summary", "Why am I seeing this?")); const list = el("ul"); for (const reason of row.explanation.why) list.append(el("li", reason)); details.append(list, el("p", row.explanation.actionBoundary, "muted")); d.append(details);
  const actions = el("div", "", "actions"), status = el("div", "No decision yet", "decision-status"), editor = el("div", "", "quantity-editor"); const accept = button("Accept suggestion", "primary"), change = button("Change quantity"), later = button("Decide later");
  accept.addEventListener("click", () => decide(row, DECISION_STATUS.ACCEPTED, null, status)); later.addEventListener("click", () => decide(row, DECISION_STATUS.DEFERRED, null, status)); change.addEventListener("click", () => { editor.replaceChildren(); const label=el("label","Your quantity"), input=document.createElement("input"), save=button("Save quantity","primary"), cancel=button("Cancel"); input.type="number";input.min="0";input.step="1";input.value=String(row.recommendation.proposedQuantity); save.addEventListener("click",()=>{const value=Number(input.value);if(!Number.isFinite(value)||value<0){status.textContent="Enter a valid quantity.";status.className="decision-status decision-error";return;}decide(row,DECISION_STATUS.MODIFIED,value,status);editor.replaceChildren();});cancel.addEventListener("click",()=>editor.replaceChildren());editor.append(label,input,save,cancel);input.focus(); });
  actions.append(accept, change, later); d.append(actions, editor, status, el("p", "Nothing here sends an order automatically. These controls only record your review decision.", "boundary-note")); root.append(d);
}

function renderFieldToday(root){const evaluated=catalogue.map((product)=>{try{return{product,advice:productAdvice(product)}}catch(error){return{product,advice:{status:"INVALID",error:error.message}}}}),ready=evaluated.filter((x)=>x.advice.status==="READY"),attention=ready.filter((x)=>x.advice.inventory.proposedRequirement>0),insufficient=evaluated.filter((x)=>x.advice.status!=="READY");const hero=el("div","","field-welcome");hero.append(el("p",`${shopProfile.shopName} · REAL LOCAL CATALOGUE`,"eyebrow"),el("h1","Today’s stock review"),el("p",`${catalogue.length} products imported. KiranaFlow is using each product’s own sales history, stock, lead time and pack size.`,"subtitle"));root.append(hero);const stats=el("div","","attention-grid");stats.append(fieldStat(String(attention.length),"need replenishment review","urgent"),fieldStat(String(insufficient.length),"need more history / checking","data"));root.append(stats);const section=el("section","","decision-card");section.append(el("h2",attention.length?"Products to review":"No replenishment proposals from the ready products"));if(attention.length){const table=el("table"),head=el("thead"),hr=el("tr");["Product","Stock","Forecast/day","Cover","Suggested review"].forEach((x)=>hr.append(el("th",x)));head.append(hr);const body=el("tbody");for(const {product,advice} of attention.slice(0,20)){const tr=el("tr");tr.append(el("td",product.name),el("td",`${product.onHand} ${product.unit}`),el("td",advice.forecast.forecast.toFixed(1)),el("td",advice.inventory.daysCover==null?"Unknown":`${advice.inventory.daysCover.toFixed(1)} days`),el("td",`${advice.inventory.proposedRequirement} ${product.unit}`));body.append(tr);}table.append(head,body);section.append(table);}section.append(el("p","Imported data remains on this browser/device. Recommendations are decision support; no order is sent.","boundary-note"));root.append(section);}
function fieldStat(value,label,tone){const c=el("div","",`attention-card ${tone}`);c.append(el("span",value,"attention-number"),el("strong",label),el("span","From imported shop data","muted"));return c;}

function decide(row, action, modifiedQuantity, status) { const decision = recordHumanDecision(row.recommendation, { action, modifiedQuantity, displayedFingerprint: row.recommendation.fingerprint, currentFingerprint: row.recommendation.fingerprint, decidedAt: demoNow(), reason: action === DECISION_STATUS.MODIFIED ? "DEMO_USER_ADJUSTMENT" : null }); decisions.set(row.recommendation.recommendationId, decision); const messages={ [DECISION_STATUS.ACCEPTED]:`✓ Suggestion accepted for review: ${row.recommendation.proposedQuantity} ${row.shop.unit}s. Nothing has been sent.`, [DECISION_STATUS.MODIFIED]:`✓ Your quantity saved: ${decision.chosenQuantity} ${row.shop.unit}s. Nothing has been sent.`, [DECISION_STATUS.DEFERRED]:"Saved for later. No order action was taken." }; status.textContent=messages[action]??`Saved: ${decision.status}`; status.className="decision-status decision-saved"; }

function renderUpdate() {
  const root = document.querySelector("#update-view"); root.replaceChildren();
  if(shopProfile&&catalogue.length){root.append(sectionHead("Keep shop data current",`The current local catalogue contains ${catalogue.length} products.`));const card=el("section","","decision-card");card.append(el("h3","Refresh from your operational CSV"),el("p","Import a new validated export when you have updated sales and closing stock. KiranaFlow will review it before replacing the local catalogue.","muted"));const setup=button("Review / import CSV","primary"),backup=button("Download backup");setup.addEventListener("click",openShopSetup);backup.addEventListener("click",downloadBackup);const acts=el("div","","actions");acts.append(setup,backup);card.append(acts,el("p","Manual per-product receipts/counts for the imported multi-product catalogue are the next field-pilot slice; the synthetic demo controls are deliberately hidden here so they cannot alter the wrong shop.","boundary-note"));root.append(card);return;}
  const shop = network.shops[0]; root.append(sectionHead("Keep stock trustworthy", "KiranaFlow can only recommend from evidence. Choose how today's information reaches the system."));
  const storage = el("div", "", `storage-status ${persistenceError ? "storage-error" : ""}`); storage.append(el("strong", persistenceError ? "Persistent storage unavailable" : "Saved on this device"), el("span", persistenceError ? persistenceError : `${ledgerEvents.length} verified ledger event${ledgerEvents.length === 1 ? "" : "s"} stored. Reloading reconstructs the state from them.`)); root.append(storage);
  const grid = el("div", "", "source-grid"); grid.append(sourceCard("POS / CSV import", "Planned route for exports from existing billing software. The parser is not connected yet.", "View status", "csv"), sourceCard("Stock received", "A supplier delivery arrived? Add the received quantity to the permanent ledger.", "Record delivery", "receipt"), sourceCard("Physical stock check", `Count what is actually on the shelf. KiranaFlow currently expects ${shop.onHand} ${shop.unit}s.`, "Enter actual count", "count"), sourceCard("Register photo", "Photograph the handwritten register, verify its reading, then keep the image for only 7 days.", "Add register photo", "photo")); root.append(grid);
  const lost = el("section", "", "lost-card"); const lostCopy = el("div", "", "lost-copy"); lostCopy.append(el("strong", "Customer asked, but it was unavailable?"), el("span", "Capture demand that billing data cannot see.")); const lostButton = button("+ Record 1 lost demand", "primary"); lostButton.disabled = !pilotDb; lostButton.addEventListener("click", async () => { try { await persistOperationalEvent(LEDGER_EVENT.LOST_DEMAND, 1, { source:"SHOPKEEPER_LOST_DEMAND" }); } catch (error) { persistenceError = error.message; refresh(); } }); lost.append(lostCopy, lostButton); root.append(lost);
  const work = el("div", "", "intake-workspace"); work.id = "intake-workspace"; root.append(work);
  const photos = el("div", "", "photo-retention"); photos.id = "photo-retention"; root.append(photos); if (pilotDb) renderPhotoRetention(photos);
  root.append(renderLedger());
}

function renderLedger() { const box=el("section", "", "ledger-panel"); box.append(el("p", "PERMANENT OPERATIONAL MEMORY", "eyebrow"), el("h3", "Activity ledger")); if (!ledgerEvents.length) { box.append(el("p", "No pilot events yet. The synthetic opening snapshot remains the current evidence.", "muted")); return box; } const table=el("table"), head=el("thead"), hr=el("tr"); ["Time", "Event", "Quantity", "Source"].forEach((x)=>hr.append(el("th",x))); head.append(hr); const body=el("tbody"); for(const event of [...ledgerEvents].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)).slice(0,20)){const tr=el("tr");tr.append(el("td",new Date(event.occurredAt).toLocaleString()),el("td",event.eventType.replaceAll("_"," ").toLowerCase()),el("td",event.quantity),el("td",formatSource(event.source)));body.append(tr);} table.append(head,body); box.append(table,el("p","Ledger events remain after register photos are purged. This local pilot has no cloud backup yet.","boundary-note")); return box; }

function sourceCard(title, copy, action, mode) { const c = el("article", "", "source-card"); c.append(el("h3", title), el("p", copy, "muted")); const b = button(action); b.addEventListener("click", () => openIntake(mode)); c.append(b); return c; }

function openIntake(mode) {
  const root = document.querySelector("#intake-workspace"); root.replaceChildren(); const shop = network.shops[0]; root.className = "intake-workspace open";
  if (mode === "receipt" || mode === "count") { root.append(el("h3", mode === "receipt" ? "Record stock received" : "Confirm physical stock"), el("p", shop.productName, "muted")); const input = document.createElement("input"); input.type = "number"; input.min = "0"; input.step = "1"; input.placeholder = mode === "receipt" ? "Quantity received" : "Quantity physically counted"; input.setAttribute("aria-label", input.placeholder); const save = button("Save to ledger", "primary"); save.disabled = !pilotDb; save.addEventListener("click", async () => { const qty = Number(input.value); if (!Number.isFinite(qty) || qty < 0 || input.value === "") { root.append(el("p", "Enter a valid non-negative quantity.", "flash danger-flash")); return; } try { await persistOperationalEvent(mode === "receipt" ? LEDGER_EVENT.STOCK_RECEIPT : LEDGER_EVENT.PHYSICAL_COUNT, qty, { source: mode === "receipt" ? "SHOPKEEPER_DELIVERY" : "SHOPKEEPER_PHYSICAL_COUNT" }); showTab("today"); } catch (error) { root.append(el("p", error.message, "flash danger-flash")); } }); root.append(input, save);
  } else if (mode === "csv") { root.append(el("h3", "POS / CSV import is not connected yet"), el("p", "This is an integration point, not a working importer in the current prototype. When built, files must pass column, unit, duplicate and timestamp checks before any ledger entry is created.", "muted"), el("p", "No file chooser is shown because choosing a file here would falsely imply that KiranaFlow can already import it.", "boundary-note"));
  } else { root.append(el("h3", "Register photo intake"), el("p", "The original image is temporary evidence. It is kept until verification and then for 7 more days.", "muted")); const f = document.createElement("input"); f.type = "file"; f.accept = "image/*"; f.setAttribute("capture", "environment"); f.disabled = !pilotDb; const state = el("p", "", "boundary-note"), verify = el("div", "", "verify-register"); f.addEventListener("change", async () => { const file = f.files?.[0]; if (!file) return; try { const photoId = makeId("PHOTO"), uploadedAt = demoNow(); await saveRegisterPhoto(pilotDb, { photoId, file, uploadedAt }); state.textContent = `Saved temporarily: ${file.name}. OCR is not connected yet; use the manual verification field below for this pilot.`; verify.replaceChildren(el("label", `Verified ${shop.productName} sales from this register photo`)); const qty = document.createElement("input"); qty.type="number"; qty.min="0"; qty.step="1"; qty.placeholder="Verified quantity sold"; const confirm=button("Confirm & write ledger", "primary"); confirm.addEventListener("click", async () => { const value=Number(qty.value); if (!Number.isFinite(value)||value<0||qty.value==="") { state.textContent="Enter the verified quantity before confirming."; return; } try { await persistOperationalEvent(LEDGER_EVENT.REGISTER_SALE, value, { source:"VERIFIED_REGISTER_PHOTO", evidencePhotoId:photoId }); await markRegisterPhotoVerified(pilotDb, photoId, demoNow()); refresh(); showTab("update"); } catch(error) { state.textContent=error.message; } }); verify.append(qty,confirm); renderPhotoRetention(document.querySelector("#photo-retention")); } catch(error) { state.textContent=`Could not save photo: ${error.message}`; } }); root.append(f, state, verify, el("div", "Photo → OCR/manual reading → human verification → permanent ledger → 7-day evidence window → photo erased", "process-strip")); }
  root.scrollIntoView({ behavior: "smooth", block: "nearest" });
}

async function renderPhotoRetention(root) { if (!root || !pilotDb) return; const rows = await listPhotoMetadata(pilotDb); root.replaceChildren(el("h3", "Register-photo retention")); if (!rows.length) { root.append(el("p", "No register photos are currently retained.", "muted")); return; } for (const row of rows.sort((a,b)=>b.uploadedAt.localeCompare(a.uploadedAt))) { const item=el("div", "", "photo-row"), retention=photoRetentionState(row,demoNow()); item.append(el("strong", row.fileName), el("span", row.status === "VERIFIED" ? `Verified · scheduled deletion after ${retention.deleteAfter}` : "Awaiting verification · not eligible for automatic deletion")); root.append(item); } }

function renderProducts() { const root=document.querySelector("#products-view");root.replaceChildren();if(shopProfile&&catalogue.length){root.append(sectionHead("Products",`${catalogue.length} products imported for ${shopProfile.shopName}.`));const table=el("table"),head=el("thead"),hr=el("tr");["SKU","Product","Stock","History","Lead time","Pack"].forEach((x)=>hr.append(el("th",x)));head.append(hr);const body=el("tbody");for(const p of catalogue){const tr=el("tr");tr.append(el("td",p.sku),el("td",p.name),el("td",`${p.onHand} ${p.unit}`),el("td",`${p.historyDays} days`),el("td",`${p.leadTimeDays} days`),el("td",String(p.packSize)));body.append(tr);}table.append(head,body);root.append(table);return;}root.append(sectionHead("Products","The synthetic demonstration contains one SKU. Use ‘Set up my shop’ to import a real catalogue."));const row=firstShopRow(),table=el("table"),head=el("thead"),hr=el("tr");["Product","Stock","Daily forecast","Cover","Evidence"].forEach((x)=>hr.append(el("th",x)));head.append(hr);const body=el("tbody"),tr=el("tr");tr.append(el("td",row.shop.productName),el("td",`${row.shop.onHand} ${row.shop.unit}s`),el("td",row.forecast.status==="FORECAST_READY"?row.forecast.forecast.toFixed(1):"Insufficient"),el("td",row.inventoryPolicy?.daysCover==null?"Unknown":`${row.inventoryPolicy.daysCover.toFixed(1)} days`),el("td",formatSource(row.shop.inventoryEvidence?.source)));body.append(tr);table.append(head,body);root.append(table);}

function renderDistributor() { const root=document.querySelector("#distributor-view");root.replaceChildren();if(shopProfile){root.append(sectionHead("Distributor connection not live yet","Your real-shop catalogue stays local on this device. KiranaFlow will not pretend that a distributor can see it before hosted synchronization and authentication are configured."));const card=el("section","","decision-card");card.append(el("h3","What will connect here"),el("p","Approved replenishment needs → authenticated shared service → mapped distributor → availability → allocation proposal.","muted"),el("p","A hosting/security choice is required before this can become live.","boundary-note"));root.append(card);return;}root.append(sectionHead("Shared demand, constrained supply","The synthetic distributor sees participating demo shops' modeled needs."));const summary=el("div","","network-summary");summary.append(fact("Distributor stock",`${dashboard.network.distributor.availableStock} bottles`),fact("Modeled shop need",`${dashboard.aggregated.totalRequirement} bottles`),fact("Allocated",`${dashboard.allocation.usedStock} bottles`));root.append(summary);const table=el("table"),head=el("thead"),hr=el("tr");["Shop","Need","Proposed allocation","Unmet"].forEach((x)=>hr.append(el("th",x)));head.append(hr);const body=el("tbody");for(const a of dashboard.allocation.allocations){const s=dashboard.shops.find((r)=>r.shop.shopId===a.shopId),tr=el("tr");tr.append(el("td",s?.shop.name??a.shopId),el("td",a.requirement),el("td",a.allocation),el("td",a.unmet));body.append(tr);}table.append(head,body);root.append(table,el("p","Synthetic demonstration. Allocation is a proposal for human review, not a dispatch instruction.","boundary-note"));}

function showTab(which) { for (const name of ["today", "update", "products", "distributor"]) { const active = name === which; document.querySelector(`#${name}-panel`).hidden = !active; document.querySelector(`#tab-${name}`).setAttribute("aria-selected", String(active)); } window.scrollTo({ top: 0, behavior: "smooth" }); }
for (const name of ["today", "update", "products", "distributor"]) document.querySelector(`#tab-${name}`).addEventListener("click", () => showTab(name));
document.querySelector("#setup-shop").addEventListener("click",openShopSetup);

function downloadText(name,text,type="text/plain"){const a=document.createElement("a"),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function downloadCsvTemplate(){const head="date,sku,product,quantity_sold,closing_stock,unit,lead_time_days,pack_size,supplier",sample="2026-10-01,OIL-1L,Cooking Oil 1L,5,24,bottle,3,6,My Distributor";downloadText("kiranaflow-import-template.csv",`${head}\n${sample}\n`,"text/csv");}
function downloadBackup(){downloadText(`kiranaflow-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,profile:shopProfile,catalogue,ledgerEvents},null,2),"application/json");}

function openShopSetup(){const d=document.createElement("dialog");d.className="setup-dialog";const heading=el("h2",shopProfile?"Shop setup & data":"Set up your shop"),intro=el("p","Import your own product history instead of using the synthetic demonstration.","muted"),nameLabel=el("label","Shop name"),name=document.createElement("input"),fileLabel=el("label","Sales + stock CSV"),file=document.createElement("input"),review=el("div","","import-review"),actions=el("div","","setup-actions"),template=button("Download CSV template"),restore=button("Restore backup"),backup=button("Download backup"),cancel=button("Cancel"),save=button("Import & use my shop","primary"),restoreFile=document.createElement("input");name.value=shopProfile?.shopName??"";name.placeholder="e.g. Gupta Kirana Store";file.type="file";file.accept=".csv,text/csv";restoreFile.type="file";restoreFile.accept=".json,application/json";restoreFile.hidden=true;save.disabled=true;backup.disabled=!shopProfile;let reviewed=null;
  template.addEventListener("click",downloadCsvTemplate);backup.addEventListener("click",downloadBackup);restore.addEventListener("click",()=>restoreFile.click());cancel.addEventListener("click",()=>d.close());
  file.addEventListener("change",async()=>{const chosen=file.files?.[0];review.replaceChildren();reviewed=null;save.disabled=true;if(!chosen)return;const result=reviewOperationalCsv(await chosen.text());review.append(el("strong",result.status==="READY"?`Ready: ${result.products.length} products from ${result.validRows} rows`:`Needs review: ${result.invalidRows??0} invalid rows`));if(result.errors?.length){const ul=el("ul");for(const error of result.errors.slice(0,12))ul.append(el("li",error));if(result.errors.length>12)ul.append(el("li",`…and ${result.errors.length-12} more`));review.append(ul);}if(result.status==="READY"){reviewed=result;save.disabled=false;}});
  save.addEventListener("click",async()=>{const shopName=name.value.trim();if(!shopName){review.replaceChildren(el("p","Enter the shop name first.","danger-text"));return;}if(!reviewed||reviewed.status!=="READY")return;try{const profile={shopName,shopId:shopProfile?.shopId??makeId("SHOP"),importedAt:demoNow()};await saveShopProfile(pilotDb,profile);await replaceCatalogue(pilotDb,reviewed.products);shopProfile=profile;catalogue=await loadCatalogue(pilotDb);d.close();refresh();showTab("today");}catch(error){review.replaceChildren(el("p",error.message,"danger-text"));}});
  restoreFile.addEventListener("change",async()=>{try{const data=JSON.parse(await restoreFile.files[0].text());if(!data.profile?.shopName||!Array.isArray(data.catalogue)||!Array.isArray(data.ledgerEvents))throw new Error("Backup structure is invalid");await saveShopProfile(pilotDb,data.profile);await replaceCatalogue(pilotDb,data.catalogue);await replaceLedger(pilotDb,data.ledgerEvents);shopProfile=await loadShopProfile(pilotDb);catalogue=await loadCatalogue(pilotDb);ledgerEvents=await loadLedger(pilotDb);d.close();refresh();}catch(error){review.replaceChildren(el("p",`Restore failed: ${error.message}`,"danger-text"));}});
  actions.append(template,restore,backup,cancel,save);d.append(heading,intro,nameLabel,name,fileLabel,file,review,actions,restoreFile);document.body.append(d);d.addEventListener("close",()=>d.remove());d.showModal();}

async function boot() { try { pilotDb = await openPilotStore(); await purgeExpiredRegisterPhotos(pilotDb, demoNow()); [ledgerEvents,shopProfile,catalogue]=await Promise.all([loadLedger(pilotDb),loadShopProfile(pilotDb),loadCatalogue(pilotDb)]); } catch (error) { persistenceError = error.message; pilotDb = null; ledgerEvents = []; shopProfile=null; catalogue=[]; } refresh(); }
boot();
