export const DEMO_POLICY = Object.freeze({
  serviceFactor: 1.28,
  reviewPeriodDays: 5,
  excessCoverDays: 30,
  demandShiftFraction: 0.25,
  leadTimeDeteriorationFraction: 0.25,
  priorityWeights: Object.freeze({
    STOCKOUT_RISK: 5,
    BELOW_REORDER_POINT: 4,
    LOST_DEMAND_OBSERVED: 3,
    DEMAND_SURGE: 2,
    LEAD_TIME_DETERIORATION: 2,
    DISTRIBUTOR_UNAVAILABLE: 3,
    FORECAST_UNRATED: 0,
  }),
});

export const DEMO_NETWORK = Object.freeze({
  generatedAt: "2026-10-05T06:00:00.000Z",
  algorithmVersion: "0.1.0",
  policyVersion: "synthetic-demo-v1",
  distributor: Object.freeze({
    distributorId: "D-DEMO-01",
    name: "Demo FMCG Distributor",
    skuId: "OIL-1L",
    availableStock: 36,
    unit: "bottle",
  }),
  shops: Object.freeze([
    Object.freeze({
      shopId: "K-DEMO-01",
      name: "Sharma Demo Stores",
      skuId: "OIL-1L",
      productName: "Cooking Oil 1 L",
      unit: "bottle",
      packSize: 6,
      onHand: 8,
      inventoryEvidence: Object.freeze({ status: "KNOWN", source: "DEMO_POS_EXPORT", observedAt: "2026-10-05T05:50:00.000Z" }),
      reserved: 0,
      incomingConfirmed: 0,
      leadTimeMeanDays: 4,
      leadTimeStdDevDays: 1,
      lostDemand: 3,
      baselineDemand: 4.2,
      recentDemand: 6.0,
      baselineLeadTimeDays: 3,
      recentLeadTimeDays: 4,
      demandHistory: Object.freeze([4, 5, 4, 5, 6, 5, 6, 6, 5, 6, 7, 6]),
    }),
    Object.freeze({
      shopId: "K-DEMO-02",
      name: "Annapurna Demo Mart",
      skuId: "OIL-1L",
      productName: "Cooking Oil 1 L",
      unit: "bottle",
      packSize: 6,
      onHand: 14,
      inventoryEvidence: Object.freeze({ status: "KNOWN", source: "DEMO_POS_EXPORT", observedAt: "2026-10-05T05:45:00.000Z" }),
      reserved: 2,
      incomingConfirmed: 0,
      leadTimeMeanDays: 3,
      leadTimeStdDevDays: 0.5,
      lostDemand: 0,
      baselineDemand: 4.8,
      recentDemand: 5.1,
      baselineLeadTimeDays: 3,
      recentLeadTimeDays: 3,
      demandHistory: Object.freeze([5, 4, 5, 5, 6, 5, 4, 5, 5, 6, 5, 5]),
    }),
    Object.freeze({
      shopId: "K-DEMO-03",
      name: "City Corner Demo Shop",
      skuId: "OIL-1L",
      productName: "Cooking Oil 1 L",
      unit: "bottle",
      packSize: 6,
      onHand: 5,
      inventoryEvidence: Object.freeze({ status: "KNOWN", source: "DEMO_PHYSICAL_COUNT", observedAt: "2026-10-05T05:40:00.000Z" }),
      reserved: 0,
      incomingConfirmed: 6,
      leadTimeMeanDays: 5,
      leadTimeStdDevDays: 1.5,
      lostDemand: 2,
      baselineDemand: 3.5,
      recentDemand: 5.2,
      baselineLeadTimeDays: 4,
      recentLeadTimeDays: 5.5,
      demandHistory: Object.freeze([3, 4, 3, 4, 4, 5, 4, 5, 5, 5, 6, 5]),
    }),
  ]),
});
